import type { ReactNode } from 'react';
import { Pressable, Text, View } from 'react-native';
import { CalendarBlank, ChartBar, DotsThreeVertical, Eye, Image as ImageIcon, ShareNetwork, Tag as TagIcon, ThumbsUp, ChatCircle, Users } from 'phosphor-react-native';
import { Avatar, Button, SurfaceCard, Tag } from '../../components';
import { colors, iconSize, radius, spacing, typography } from '../../tokens';

export function CreatePostCard() {
  return <SurfaceCard elevated={false}><View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }}><Avatar size="MD" type="Initials" name="Niraj P" /><View style={{ flex: 1, alignItems: 'flex-start', gap: spacing.md, minHeight: 40, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surfaceSecondary }}><Text style={[typography.bodyLarge, { color: colors.contentPlaceholder, flex: 1 }]}>What do you have to say?</Text><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.lg }}>{[ImageIcon, ChartBar, CalendarBlank, TagIcon].map((Icon, index) => <Icon key={index} size={iconSize.lg} color={colors.contentAction} weight="regular" />)}</View></View></View></SurfaceCard>;
}

export type FeedCardProps = { authorArtwork: ReactNode; authorName: string; admin?: boolean; subline: string; meta?: ReactNode; children: ReactNode; footer?: 'standard' | 'listing' | 'none'; likeCount?: number; replyCount?: number; customFooter?: ReactNode };

export function FeedCard({ authorArtwork, authorName, admin, subline, meta, children, footer = 'standard', likeCount = 0, replyCount = 0, customFooter }: FeedCardProps) {
  return <SurfaceCard elevated><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>{authorArtwork}<View style={{ flex: 1, gap: 2 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs, flexWrap: 'wrap' }}><Text style={typography.bodyDefaultBold}>{authorName}</Text>{admin ? <Tag kind="Neutral" variant="Solid" label="Admin" /> : null}</View><Text style={[typography.caption, { color: colors.contentSecondary }]}>{subline}</Text></View><DotsThreeVertical size={iconSize.md} color={colors.contentTertiary} weight="bold" /></View><View style={{ gap: spacing.xs }}>{meta}{children}</View>{customFooter ?? (footer === 'listing' ? <View style={{ flexDirection: 'row', gap: spacing.sm, paddingTop: spacing.md }}><View style={{ flex: 1 }}><Button kind="Tertiary" size="MD" label="Share" fullWidth /></View><View style={{ flex: 1 }}><Button kind="Secondary" size="MD" label="Message" fullWidth /></View></View> : footer === 'standard' ? <><View style={{ height: 1, backgroundColor: colors.borderSubtle }} /><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.lg }}><Pressable accessibilityRole="button" accessibilityLabel="Like" style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}><ThumbsUp size={iconSize.md} color={colors.contentSecondary} weight="regular" />{likeCount > 0 ? <Text style={[typography.bodySmall, { color: colors.contentPrimary }]}>{likeCount}</Text> : null}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="Reply" style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}><ChatCircle size={iconSize.md} color={colors.contentSecondary} weight="regular" />{replyCount > 0 ? <Text style={[typography.bodySmall, { color: colors.contentPrimary }]}>{replyCount}</Text> : null}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="Share"><ShareNetwork size={iconSize.md} color={colors.contentSecondary} weight="regular" /></Pressable></View></> : null)}</SurfaceCard>;
}

export function FeedEventActions({ attendeeCount, viewCount }: { attendeeCount: number; viewCount: number }) {
  return <><View style={{ flexDirection: 'row', gap: spacing.sm }}><Button kind="Tertiary" size="MD" label={String(attendeeCount)} showLeftIcon leftIcon={Users} /><View style={{ flex: 1 }}><Button kind="Tertiary" size="MD" label="Going?" fullWidth /></View></View><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.lg }}><Pressable accessibilityRole="button" accessibilityLabel="Like"><ThumbsUp size={iconSize.md} color={colors.contentSecondary} weight="regular" /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Share"><ShareNetwork size={iconSize.md} color={colors.contentSecondary} weight="regular" /></Pressable></View><View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.xs }}><Eye size={iconSize.sm} color={colors.contentTertiary} weight="regular" /><Text style={[typography.caption, { color: colors.contentTertiary }]}>{viewCount}</Text></View></View></>;
}
